build_task: pipelines/gradle/tasks/gradle-assemble.yml # don't change
deploy_dev_task: pipelines/cf/tasks/blue-green-deploy.yml # don't change

app_name: attendee-viewer
jar_name: kattia-attendee-viewer

github_app_repo_uri: https://github.com/Pegasus51B/attendee-viewer-initial
github_app_repo_branch: master # don't change

github_pipelines_repo_uri: https://github.com/kgmr2015/training-pipelines-initial
github_pipelines_repo_branch: master # don't change

version_bucket: rscale-training-bucket # don't change
version_bucket_region_name: us-west-2 # don't change

version_key: kattia.marinrobles-config-version 
initial_version: 0.0.1

artifact_regexp: kattia-attendee-viewer-(.*).jar
artifact_bucket: rscale-training-bucket # don't change
artifact_bucket_region_name: us-west-2 # don't change

cf_dev_api: https://api.run.pivotal.io
cf_dev_organization: rscale-training-3
cf_dev_space: kattia.marinrobles@cgi.com
cf_dev_hostname: attendee-viewerkattia
cf_dev_domain: cfapps.io
cf_dev_manifest: manifest.yml

feign:
  hystrix:
    enabled: true
    
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: ${CLIENT_ID}
      clientSecret: ${CLIENT_SECRET}
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
      preEstablishedRedirectUri: https://https://github.com/kgmr2015/attendee-viewer-initial/login
      registered-redirect-uri: https://https://github.com/kgmr2015/attendee-viewer-initial/login
      use-current-uri: false
    resource:
      userInfoUri: https://api.github.com/user    
    